version: "2"

services:
  ss:
    image: orvice/knock
    restart: always
    volumes:
      - ./log:/var/log
    environment:
      - DST=xxx
      - MU_URI=https://demo.sspanel.xyz/mu/v2/
      - MU_NODE_ID=1
      - MU_TOKEN=forLove
      - LOG_FILE=/var/log/knock.log

    network_mode: host
 